service:
  name: product-service
  version: 0.0.1

db:
  uri: postgresql://postgres:postgres@localhost:5432/postgres
  prefix: public.

cache:
  hostname: localhost:6379
  password: ""
  defaultExpiration: 60s

tracing:
  target: localhost:4317